# Add your donation/funding channels below
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Uncomment and fill in your channels:
# github: your_username
# patreon: your_username
# buy_me_a_coffee: your_username
# liberapay: your_username
# custom: ['https://paypal.me/yourlink']
